### ISSUE TITLE
Request for entity limits <3

### ISSUE THREAD

**Issue by wearenoobsuk** [BentoBoxWorld/Limits#129]
**Is your feature request related to a problem? Please describe.**
I have ranks on my server as most skyblock servers do, I don't want everyone to have a set amount of entities allowed. I want people who progress to the ranks to be allowed more mobs, Aka +1 villager per rank

**Describe the solution you'd like**
I can think of two methods, A group tree inside of limits like

name:group1
limits:
villager=1
creeper=2
etc

Then the permission limits.group1

Or, an independent permission for each mob, limits.creeper.1

**Describe alternatives you've considered**
Haven't tried any alternatives

**Additional context**
I know alot of people would benefit from this, And my people won't stop bugging me about only having 1 villager lol, I'm aware i can bump that up, but then i will have to bump it back down if this gets released. (and kill alot of peoples mobs in the process)

thankyou! <3

**Comment by tastybento** [comment]
There are permissions that can be used. You can give permissions to your ranks to allow them higher limits.

**Comment by wearenoobsuk** [comment]
I stand mistaken, there is, But after testing, It seems to be fairly bugged, If my villager limit is 2. I lets me spawn in villagers with eggs, and just says 2/1 on limits, And villager breeding also will let them breed infinitely past their limit.

**Comment by tastybento** [comment]
For the spawn egg, you may have a bypass permission. Check that you are not Op and don't have the [gamemode].mod.bypass permission. 

For the second issue, I'm pretty sure that when villagers spawn by themselves it is classed by the server as natural spawning rather than breeding and that is not limited by Limits.

**Comment by tastybento** [comment]
If you'd like this feature added then it can be done.

**Comment by wearenoobsuk** [comment]
> If you'd like this feature added then it can be done.

Would help massively! As there's no point having a villager limit if ya can breed past it haha.

Thankyou

**Comment by tastybento** [comment]
Okay, I'll try. Now I need to work out how to make villagers breed so I can investigate this!

**Comment by tastybento** [comment]
Can you share how to make villagers breed beyond the limit? I put two villagers in a room with beds and food. After a while they pick up the food and try to breed, but fail because I set the limit to 2 villagers. Have a look at the video. I watched them through the window. Maybe there's some other way to have them breed?

By the way, if an Op is within 5 blocks of the breeding, or someone with bypass perms, the breeding will happen. I had to drop myself to make them create angry clouds.

https://user-images.githubusercontent.com/4407265/116770927-23a80a00-a9fc-11eb-94fd-ef1636f0e600.mov

**Comment by wearenoobsuk** [comment]
> Can you share how to make villagers breed beyond the limit? I put two villagers in a room with beds and food. After a while they pick up the food and try to breed, but fail because I set the limit to 2 villagers. Have a look at the video. I watched them through the window. Maybe there's some other way to have them breed?
> 
> By the way, if an Op is within 5 blocks of the breeding, or someone with bypass perms, the breeding will happen. I had to deop myself to make them create angry clouds.
> 
>  Screen.Recording.2021-04-30.at.9.31.39.PM.mov

I didn't even consider deopping. It doesn't let me add more villagers with spawnmob command  and says villagers limited to 2 so I assumed I didn't have any kind of bypass. I'll try with deopping though and let you know. Thanks!

**Comment by wearenoobsuk** [comment]
This
