### ISSUE TITLE
[Critical] farm block bug , need hot fix , please

### ISSUE THREAD

**Issue by p82183645** [BentoBoxWorld/Limits#44]
if set 
WHEAT: 10  , the can't limits 10  When you plant x10 and then dismantle it, he will think you have 10
Then you never fram again

Please add limits on crops fram
only happen the all about fram block

WHEAT
SUGAR_CANE
BAMBOO
CARROT
POTATO
SWEET_BERRIES
NETHER_WART
ALL

**Comment by tastybento** [comment]
I never designed Limits to limit crops. Limits was originally designed for limiting blocks that cause lag. Anyway, I'll see what I can do. I cannot promise a quick or "hot fix".

Here are my findings so far:

**Sugar cane**
Canes can be placed on top of each other, but when broken at the bottom, the full height is broken but not recognized. This is a bug.

**Wheat**
WHEAT_SEEDS are planted but yield the block of type WHEAT. But if a WHEAT block is broken before it is fully grown, it yields WHEAT_SEEDS, not WHEAT. This will need special handling.

**Bamboo**
For bamboo, limit should be on BAMBOO_SAPLING (not BAMBOO) because that is what bamboo is at the start. It is correctly tracked.

**Carrots and potatoes**
Use CARROTS and POTATOES instead of CARROT and POTATO. Currently, they do not show in the GUI. This is a bug and I'll fix it.

**Sweet berries**
Similar to carrots, SWEET_BERRIES must be SWEET_BERRY_BUSH. This also does not show in the GUI yet. Also, like WHEAT, if they are broken before berries grow, they break as SWEET_BERRY_BUSH, but if they break when they have berries, they break as SWEET_BERRIES. This will require special handling.

**Netherwart**
Seems to work okay. I'm testing still because they cannot be grown quickly.

**Others**
It's likely that other crops need addressing, like beetroot. They'll need to be checked out.


-

**Comment by tastybento** [comment]
Okay, I've fixed these issues. There is a fundamental problem though and that is players can break blocks under crops and the broken crops cannot be caught. Well, they can, but using a lot of code. For now, I've added a user command "recount" that players can use (cool down = 2 minutes) to check if the count is okay. Disable with perms if you like.
